/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aas;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sreej
 */
public class adminshow extends javax.swing.JFrame
{

    static int choice, cchoice;

    /**
     * Creates new form adminshow
     */
    public adminshow()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        sid2 = new javax.swing.JTextField();
        sid1 = new javax.swing.JLabel();
        cid2 = new javax.swing.JTextField();
        cid1 = new javax.swing.JLabel();
        pc = new javax.swing.JRadioButton();
        ac = new javax.swing.JRadioButton();
        as = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        cid11 = new javax.swing.JLabel();
        cid12 = new javax.swing.JTextField();
        btn_exit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/info.png"))); // NOI18N
        jLabel1.setText("Show Attendance Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 107, 2010, 101);

        jButton3.setBackground(new java.awt.Color(189, 209, 246));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/back.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 800, 284, 69);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Particular Student");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(550, 272, 266, 55);

        sid2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        sid2.setForeground(new java.awt.Color(0, 0, 0));
        sid2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sid2ActionPerformed(evt);
            }
        });
        getContentPane().add(sid2);
        sid2.setBounds(809, 328, 338, 58);

        sid1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sid1.setForeground(new java.awt.Color(255, 255, 255));
        sid1.setText("Student ID:");
        getContentPane().add(sid1);
        sid1.setBounds(619, 328, 172, 58);

        cid2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cid2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(cid2);
        cid2.setBounds(881, 475, 338, 45);

        cid1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cid1.setForeground(new java.awt.Color(255, 255, 255));
        cid1.setText("Course ID:");
        getContentPane().add(cid1);
        cid1.setBounds(732, 475, 137, 45);

        buttonGroup2.add(pc);
        pc.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        pc.setForeground(new java.awt.Color(255, 255, 255));
        pc.setText("Particular Course");
        pc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pcActionPerformed(evt);
            }
        });
        getContentPane().add(pc);
        pc.setBounds(619, 415, 198, 53);

        buttonGroup2.add(ac);
        ac.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ac.setForeground(new java.awt.Color(255, 255, 255));
        ac.setText("All Course");
        ac.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                acActionPerformed(evt);
            }
        });
        getContentPane().add(ac);
        ac.setBounds(619, 538, 206, 45);

        buttonGroup1.add(as);
        as.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        as.setForeground(new java.awt.Color(255, 255, 255));
        as.setText("All Student");
        as.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                asActionPerformed(evt);
            }
        });
        getContentPane().add(as);
        as.setBounds(550, 601, 275, 63);

        jButton4.setBackground(new java.awt.Color(189, 209, 246));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/login.png"))); // NOI18N
        jButton4.setText("Next");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(980, 800, 284, 69);

        cid11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cid11.setForeground(new java.awt.Color(255, 255, 255));
        cid11.setText("Course ID:");
        getContentPane().add(cid11);
        cid11.setBounds(645, 671, 137, 45);

        cid12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cid12.setForeground(new java.awt.Color(0, 0, 0));
        cid12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cid12ActionPerformed(evt);
            }
        });
        getContentPane().add(cid12);
        cid12.setBounds(794, 671, 338, 45);

        btn_exit.setBackground(new java.awt.Color(189, 209, 246));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/exit.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(1690, 970, 130, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/dark-blue-tech-circuit-board-technology-animated-background-video-graphic-design-ultra-hd-4k-3840x2160_sgelpuywg_thumbnail-full05.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 2000, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        Showselection ob = new Showselection();
        this.hide();
        ob.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sid2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sid2ActionPerformed
    {//GEN-HEADEREND:event_sid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sid2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
        choice = 1;
        sid1.setEnabled(true);
        sid2.setEnabled(true);
        cid1.setEnabled(true);
        cid2.setEnabled(true);
        pc.setEnabled(true);
        ac.setEnabled(true);
        cid11.setEnabled(false);
        cid12.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void asActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_asActionPerformed
    {//GEN-HEADEREND:event_asActionPerformed
        choice = 2;
        cid11.setEnabled(true);
        cid12.setEnabled(true);
        sid1.setEnabled(false);
        sid2.setEnabled(false);
        cid1.setEnabled(false);
        cid2.setEnabled(false);
        pc.setEnabled(false);
        ac.setEnabled(false);
        sid2.setText("");
        cid2.setText("");
    }//GEN-LAST:event_asActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_acActionPerformed
    {//GEN-HEADEREND:event_acActionPerformed
        cchoice = 2;
        cid1.setEnabled(false);
        cid2.setEnabled(false);
        cid2.setText("");
    }//GEN-LAST:event_acActionPerformed

    private void pcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pcActionPerformed
    {//GEN-HEADEREND:event_pcActionPerformed
        cchoice = 1;
        cid1.setEnabled(true);
        cid2.setEnabled(true);
    }//GEN-LAST:event_pcActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        db_access db = new db_access();
        if (choice == 1)
        {
            if (cchoice == 1)
            {
                if ("".equals(sid2.getText()))
                {
                    JOptionPane.showMessageDialog(null, "Please enter Student ID", "", JOptionPane.INFORMATION_MESSAGE);
                } else
                {
                    try
                    {
                        Connection con = db.connect();
                        int _course = Integer.parseInt(cid2.getText());
                        this.hide();
                        int id = Integer.parseInt(sid2.getText());
                        Student1 ob = new Student1(id);
                        ob.showSingleCourseAtt(con, _course, 2);

                    } catch (SQLException se)
                    {
                        System.out.println("in btn_next: " + se);
                    }
                }

            } else if (cchoice == 2)
            {

                if ("".equals(sid2.getText()))
                {
                    JOptionPane.showMessageDialog(null, "Please enter Student ID", "", JOptionPane.INFORMATION_MESSAGE);
                } else
                {
                    try
                    {
                        Connection con = db.connect();
                        //int _course= Integer.parseInt(course);
                        this.hide();
                        int sid = Integer.parseInt(sid2.getText());
                        Student1 ob = new Student1(sid);
                        ob.showAllCourseAtt(con, 1);
                    } catch (SQLException e)
                    {
                    }
                }

            }
        } else if (choice == 2)
        {
            try
            {
                Connection con = db.connect();
                int course = Integer.parseInt(cid12.getText());
                Teacher2 ob = new Teacher2(course);
                this.hide();
                ob.showCourseAtt(con, 1);
            } catch (Exception e)
            {
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cid12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cid12ActionPerformed
    {//GEN-HEADEREND:event_cid12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cid12ActionPerformed
    private JFrame frame;
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_exitActionPerformed
    {//GEN-HEADEREND:event_btn_exitActionPerformed
        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to exit?","Automated Attendance System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION )
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(adminshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(adminshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(adminshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(adminshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new adminshow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ac;
    private javax.swing.JRadioButton as;
    private javax.swing.JButton btn_exit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cid1;
    private javax.swing.JLabel cid11;
    private javax.swing.JTextField cid12;
    private javax.swing.JTextField cid2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton pc;
    private javax.swing.JLabel sid1;
    private javax.swing.JTextField sid2;
    // End of variables declaration//GEN-END:variables
}
