/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Md. Ziad Karim
 */
public class ParticularStudentInfo extends javax.swing.JFrame
{

    /**
     * Creates new form ParticularStudentInfo
     */
    static String id, course, t_name, percenatage;
    static int total, present, t_id, key;

    public ParticularStudentInfo()
    {
        initComponents();
        sid.setText(id);
        c.setText(course);
        String tot = Integer.toString(total);
        String pre = Integer.toString(present);
        tc.setText(tot);
        lbl_present.setText(pre);
        lbl_percentage.setText(percenatage);
        if (key == 1)
        {
            lbl_tid.setText("Teacher id: ");
            String tid = Integer.toString(t_id);
            lbl_show_tid.setText(tid);
            lbl_tname.setText("Teacher name: ");
            lbl_show_tname.setText(t_name);
        }
    }

    ParticularStudentInfo(String _course, String _id, int _total, int _present, String _perc, int _key)
    {
        id = _id;
        course = _course;
        total = _total;
        present = _present;
        percenatage = _perc;
        key = _key;
    }

    public void teacherid(int id, String name)
    {
        t_id = id;
        t_name = name;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_tid = new javax.swing.JLabel();
        lbl_show_tid = new javax.swing.JLabel();
        tc = new javax.swing.JLabel();
        lbl_percentage = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        c = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sid = new javax.swing.JLabel();
        lbl_tname = new javax.swing.JLabel();
        lbl_show_tname = new javax.swing.JLabel();
        lbl_present = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(189, 209, 246));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Attendance Information");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 1908, 133);

        jLabel1.setBackground(new java.awt.Color(189, 209, 246));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Class : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 590, 241, 64);

        jLabel3.setBackground(new java.awt.Color(189, 209, 246));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Percentage:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 790, 241, 65);

        lbl_tid.setBackground(new java.awt.Color(189, 209, 246));
        lbl_tid.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_tid.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_tid);
        lbl_tid.setBounds(320, 290, 241, 64);

        lbl_show_tid.setBackground(new java.awt.Color(204, 204, 204));
        lbl_show_tid.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_show_tid.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_show_tid);
        lbl_show_tid.setBounds(690, 290, 836, 64);

        tc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tc.setForeground(new java.awt.Color(255, 255, 255));
        tc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(tc);
        tc.setBounds(690, 590, 836, 64);

        lbl_percentage.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_percentage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_percentage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbl_percentage);
        lbl_percentage.setBounds(690, 790, 840, 65);

        btn_exit.setBackground(new java.awt.Color(189, 209, 246));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/exit.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(1030, 940, 260, 70);

        btn_back.setBackground(new java.awt.Color(189, 209, 246));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/back.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(640, 940, 250, 70);

        c.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        c.setForeground(new java.awt.Color(255, 255, 255));
        c.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(c);
        c.setBounds(690, 500, 836, 64);

        jLabel5.setBackground(new java.awt.Color(189, 209, 246));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Course:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 500, 241, 64);

        jLabel6.setBackground(new java.awt.Color(189, 209, 246));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student ID : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 400, 241, 64);

        sid.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        sid.setForeground(new java.awt.Color(255, 255, 255));
        sid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(sid);
        sid.setBounds(690, 400, 836, 64);

        lbl_tname.setBackground(new java.awt.Color(189, 209, 246));
        lbl_tname.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_tname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_tname);
        lbl_tname.setBounds(320, 190, 330, 60);

        lbl_show_tname.setBackground(new java.awt.Color(204, 204, 204));
        lbl_show_tname.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_show_tname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_show_tname);
        lbl_show_tname.setBounds(690, 190, 836, 64);

        lbl_present.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_present.setForeground(new java.awt.Color(255, 255, 255));
        lbl_present.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbl_present);
        lbl_present.setBounds(690, 690, 840, 65);

        jLabel4.setBackground(new java.awt.Color(189, 209, 246));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Present : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 690, 241, 65);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/dark-blue-tech-circuit-board-technology-animated-background-video-graphic-design-ultra-hd-4k-3840x2160_sgelpuywg_thumbnail-full05.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 2000, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "Automated Attendance System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        if (key == 1)
        {
            Teacher ob = new Teacher();
            ob.show();
            this.hide();
        } else if(key==0)
        {
            Student ob = new Student();
            ob.show();
            this.hide();
        }
        else{
            adminshow ob = new adminshow();
            ob.show();
            this.hide();
        }
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ParticularStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ParticularStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ParticularStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ParticularStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ParticularStudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel c;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_percentage;
    private javax.swing.JLabel lbl_present;
    private javax.swing.JLabel lbl_show_tid;
    private javax.swing.JLabel lbl_show_tname;
    private javax.swing.JLabel lbl_tid;
    private javax.swing.JLabel lbl_tname;
    private javax.swing.JLabel sid;
    private javax.swing.JLabel tc;
    // End of variables declaration//GEN-END:variables
}
