/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sreej
 */
public class start_attendence extends javax.swing.JFrame
{

    /**
     * Creates new form start_attendence
     */
    public start_attendence()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        txt_course_id = new javax.swing.JTextField();
        txt_period = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_start1 = new javax.swing.JButton();
        btn_start2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 980));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 980));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Course:");
        jLabel1.setMaximumSize(new java.awt.Dimension(177, 44));
        jLabel1.setMinimumSize(new java.awt.Dimension(177, 44));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(640, 370, 245, 81);

        txt_course_id.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txt_course_id.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_course_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_course_id);
        txt_course_id.setBounds(990, 370, 245, 81);

        txt_period.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(txt_period);
        txt_period.setBounds(990, 500, 245, 81);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Period(s):");
        jLabel2.setMaximumSize(new java.awt.Dimension(177, 44));
        jLabel2.setMinimumSize(new java.awt.Dimension(177, 44));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(640, 500, 245, 81);

        btn_start.setBackground(new java.awt.Color(189, 209, 246));
        btn_start.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/start.png"))); // NOI18N
        btn_start.setText("START");
        btn_start.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_start.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start);
        btn_start.setBounds(1020, 700, 206, 68);

        btn_back.setBackground(new java.awt.Color(189, 209, 246));
        btn_back.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/back.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(640, 700, 223, 68);

        btn_exit.setBackground(new java.awt.Color(189, 209, 246));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/exit.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(1539, 867, 150, 50);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course:");
        jLabel6.setMaximumSize(new java.awt.Dimension(177, 44));
        jLabel6.setMinimumSize(new java.awt.Dimension(177, 44));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 370, 245, 81);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/dark-blue-tech-circuit-board-technology-animated-background-video-graphic-design-ultra-hd-4k-3840x2160_sgelpuywg_thumbnail-full05.png"))); // NOI18N
        jLabel5.setMinimumSize(new java.awt.Dimension(1920, 980));
        jLabel5.setPreferredSize(new java.awt.Dimension(1920, 980));
        jLabel5.setRequestFocusEnabled(false);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 2000, 1080);

        btn_start1.setBackground(new java.awt.Color(189, 209, 246));
        btn_start1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_start1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/start.png"))); // NOI18N
        btn_start1.setText("START");
        btn_start1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_start1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_start1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start1);
        btn_start1.setBounds(1030, 700, 206, 68);

        btn_start2.setBackground(new java.awt.Color(189, 209, 246));
        btn_start2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_start2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/start.png"))); // NOI18N
        btn_start2.setText("START");
        btn_start2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_start2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_start2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start2);
        btn_start2.setBounds(1020, 700, 206, 68);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_course_idActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_course_idActionPerformed
    {//GEN-HEADEREND:event_txt_course_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_course_idActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_startActionPerformed
    {//GEN-HEADEREND:event_btn_startActionPerformed
        int c_id = Integer.parseInt(txt_course_id.getText());
        int period = Integer.parseInt(txt_period.getText());
        
        NetworkHandler nw = new NetworkHandler();
        nw.listen(80, 1, c_id, period);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_backActionPerformed
    {//GEN-HEADEREND:event_btn_backActionPerformed
        Teacher1 ob = new Teacher1();
        ob.show();
        this.hide();
    }//GEN-LAST:event_btn_backActionPerformed
    private JFrame frame;
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_exitActionPerformed
    {//GEN-HEADEREND:event_btn_exitActionPerformed
        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to exit?","Automated Attendance System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION )
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_start1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_start1ActionPerformed
    {//GEN-HEADEREND:event_btn_start1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_start1ActionPerformed

    private void btn_start2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_start2ActionPerformed
    {//GEN-HEADEREND:event_btn_start2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_start2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(start_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(start_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(start_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(start_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new start_attendence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_start1;
    private javax.swing.JButton btn_start2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_course_id;
    private javax.swing.JTextField txt_period;
    // End of variables declaration//GEN-END:variables
}
