package aas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Md. Ziad Karim
 */
public class Student extends javax.swing.JFrame
{

    /**
     * Creates new form Student
     */
    static String name;
    static int choice = 0, id;

//    public Student(String _name, String _id, String _dept)
//    {
//        name = _name;
//        id = _id;
//        dept = _dept;
//
//    }
    public Student()
    {
        initComponents();
        c1.setEnabled(false);
        c2.setEnabled(false);

        lbl_name.setText("Name : " + name);
        lbl_id.setText("ID : " + id);
        d.setText("Department : CSE");
    }

    public Student(int _id)
    {
        id = _id;
        try
        {
            db_access db = new db_access();
            Connection con = db.connect();

            String query = "select name from student where st_id=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, id);

            ResultSet rs = ps.executeQuery();
            rs.next();

            name = rs.getString(1);
            db.close(con);
        } catch (SQLException se)
        {
            System.out.println("in Student cons: " + se);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        all = new javax.swing.JRadioButton();
        particular = new javax.swing.JRadioButton();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        d = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student");
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/student.png"))); // NOI18N
        jLabel2.setText(" Student");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(798, 44, 380, 70);

        buttonGroup1.add(all);
        all.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        all.setForeground(new java.awt.Color(255, 255, 255));
        all.setText("All course");
        all.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                allActionPerformed(evt);
            }
        });
        getContentPane().add(all);
        all.setBounds(1031, 531, 422, 69);

        buttonGroup1.add(particular);
        particular.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        particular.setForeground(new java.awt.Color(255, 255, 255));
        particular.setText("Particular Course");
        particular.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                particularActionPerformed(evt);
            }
        });
        getContentPane().add(particular);
        particular.setBounds(1031, 317, 422, 69);

        c1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setText("Course:");
        getContentPane().add(c1);
        c1.setBounds(1244, 431, 162, 47);

        c2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        c2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(1411, 430, 373, 47);

        btn_next.setBackground(new java.awt.Color(189, 209, 246));
        btn_next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/login.png"))); // NOI18N
        btn_next.setText("Next");
        btn_next.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_next.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_nextActionPerformed(evt);
            }
        });
        getContentPane().add(btn_next);
        btn_next.setBounds(742, 835, 367, 74);

        btn_back.setBackground(new java.awt.Color(189, 209, 246));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/back.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(213, 835, 367, 74);

        lbl_id.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_id);
        lbl_id.setBounds(155, 433, 479, 58);

        lbl_name.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_name);
        lbl_name.setBounds(155, 351, 479, 53);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("_____________________________________________________________________________");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(117, 317, 575, 15);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_____________________________________________________________________________");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(117, 571, 575, 15);

        jLabel7.setText("__________________________________________________________");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(742, 116, 408, 15);

        btn_exit.setBackground(new java.awt.Color(189, 209, 246));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/exit.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(1274, 835, 367, 74);

        d.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        d.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(d);
        d.setBounds(155, 509, 479, 49);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1920, 0);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/dark-blue-tech-circuit-board-technology-animated-background-video-graphic-design-ultra-hd-4k-3840x2160_sgelpuywg_thumbnail-full05.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 2000, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void particularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_particularActionPerformed
        c2.setEnabled(true);
        c1.setEnabled(true);
        choice = 1;
    }//GEN-LAST:event_particularActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
        c1.setEnabled(false);
        c2.setEnabled(false);
        choice = 2;
    }//GEN-LAST:event_allActionPerformed
    private JFrame frame;
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "Automated Attendance System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        Login ob = new Login();
        Login loginob = new Login(3);
        this.hide();
        ob.show();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        String course;
        course = c2.getText();
        db_access db = new db_access();

        if (choice == 0)
        {
            JOptionPane.showMessageDialog(null, "Please select an option", "", JOptionPane.INFORMATION_MESSAGE);
        } else if (choice == 1)
        {
            if ("".equals(course))
            {
                JOptionPane.showMessageDialog(null, "Please enter the course", "", JOptionPane.INFORMATION_MESSAGE);
            } else
            {
                try
                {
                    Connection con = db.connect();
                    int _course = Integer.parseInt(course);
                    this.hide();

                    Student1 ob = new Student1(id);
                    ob.showSingleCourseAtt(con, _course, 0);

                } catch (SQLException se)
                {
                    System.out.println("in btn_next: " + se);
                }

            }
        } else if (choice == 2)
        {

            try
            {
                Connection con = db.connect();
                //int _course= Integer.parseInt(course);
                this.hide();
                Student1 ob = new Student1(id);
                ob.showAllCourseAtt(con, 0);
            } catch (SQLException e)
            {
            }
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton all;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_next;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel c1;
    private javax.swing.JTextField c2;
    private javax.swing.JLabel d;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JRadioButton particular;
    // End of variables declaration//GEN-END:variables
}
