package aas;

import static aas.Student.id;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Md. Ziad Karim
 */
public class Teacher extends javax.swing.JFrame
{

    /**
     * Creates new form Teacher
     */
    static String name;
    static int choice, id, course;

    public Teacher()
    {
        initComponents();
        lbl_id.setText("ID : " + id);
        lbl_course.setText("Course : " + course);
        lbl_name.setText("Name : " + name);
        lbl_select_id.setEnabled(false);
        txt_st_id.setEnabled(false);
    }

//    public Teacher(String _name, String _dept, String _course)
//    {
//        name = _name;
//        course = _course;
//        dept = _dept;
//
//    }
    Teacher(int t_id)
    {
        id = t_id;
        try
        {
            db_access db = new db_access();
            Connection con = db.connect();

            String query = "select course_id, name from Teacher where t_id=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, id);

            ResultSet rs = ps.executeQuery();
            rs.next();
            course = rs.getInt(1);
            name = rs.getString(2);

            db.close(con);
        } catch (SQLException se)
        {
            System.out.println("in Teacher cons: " + se);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_particular = new javax.swing.JRadioButton();
        lbl_select_id = new javax.swing.JLabel();
        txt_st_id = new javax.swing.JTextField();
        btn_all = new javax.swing.JRadioButton();
        btn_exit = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbl_course = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(null);

        btn_particular.setBackground(new java.awt.Color(189, 209, 246));
        buttonGroup1.add(btn_particular);
        btn_particular.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_particular.setForeground(new java.awt.Color(255, 255, 255));
        btn_particular.setText("Particular Student");
        btn_particular.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_particularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_particular);
        btn_particular.setBounds(903, 317, 422, 69);

        lbl_select_id.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_select_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_select_id.setText("Student ID:");
        getContentPane().add(lbl_select_id);
        lbl_select_id.setBounds(1039, 431, 226, 47);

        txt_st_id.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txt_st_id.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_st_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_st_id);
        txt_st_id.setBounds(1283, 430, 373, 47);

        btn_all.setBackground(new java.awt.Color(189, 209, 246));
        buttonGroup1.add(btn_all);
        btn_all.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_all.setForeground(new java.awt.Color(255, 255, 255));
        btn_all.setText("All Students");
        btn_all.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_allActionPerformed(evt);
            }
        });
        getContentPane().add(btn_all);
        btn_all.setBounds(903, 531, 422, 69);

        btn_exit.setBackground(new java.awt.Color(189, 209, 246));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/exit.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(1274, 835, 367, 74);

        btn_next.setBackground(new java.awt.Color(189, 209, 246));
        btn_next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/login.png"))); // NOI18N
        btn_next.setText("Next");
        btn_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_next.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_nextActionPerformed(evt);
            }
        });
        getContentPane().add(btn_next);
        btn_next.setBounds(742, 835, 367, 74);

        btn_back.setBackground(new java.awt.Color(189, 209, 246));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/back.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(213, 835, 367, 74);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_____________________________________________________________________________");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(117, 571, 575, 15);

        lbl_course.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_course.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_course);
        lbl_course.setBounds(155, 509, 479, 49);

        lbl_name.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_name);
        lbl_name.setBounds(155, 433, 479, 58);

        lbl_id.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_id);
        lbl_id.setBounds(155, 351, 479, 53);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("_____________________________________________________________________________");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(117, 317, 575, 15);

        jLabel7.setText("__________________________________________________________");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(742, 116, 408, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/teacher.png"))); // NOI18N
        jLabel2.setText(" Teacher");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(768, 44, 390, 80);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/dark-blue-tech-circuit-board-technology-animated-background-video-graphic-design-ultra-hd-4k-3840x2160_sgelpuywg_thumbnail-full05.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 2000, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_particularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_particularActionPerformed
        txt_st_id.setEnabled(true);
        lbl_select_id.setEnabled(true);
        choice = 1;
    }//GEN-LAST:event_btn_particularActionPerformed

    private void txt_st_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_st_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_st_idActionPerformed

    private void btn_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allActionPerformed
        lbl_select_id.setEnabled(false);
        txt_st_id.setEnabled(false);
        choice = 2;
    }//GEN-LAST:event_btn_allActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "Automated Attendance System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        String s_id;
        s_id = txt_st_id.getText();
        db_access db = new db_access();
        if (choice == 1)
        {
            if ("".equals(s_id))
            {
                JOptionPane.showMessageDialog(null, "Please enter the Student ID", "", JOptionPane.INFORMATION_MESSAGE);
            } else
            {
//                ParticularStudentInfo pob;
//                pob = new ParticularStudentInfo(course,id);
//                ParticularStudentInfo ob=new ParticularStudentInfo();
                try
                {
                    Connection con = db.connect();
                    this.hide();

                    Teacher2 ob = new Teacher2(id, course, name);
                    int sid = Integer.parseInt(s_id);
                    ob.showStudentAttendance(con, sid, 1);
                } catch (SQLException se)
                {
                    System.out.println("in btn_next: " + se);
                }

            }
        } else if (choice == 2)
        {
            try
            {
                Connection con = db.connect();
                Teacher2 ob = new Teacher2(id, course, name);
                this.hide();
                ob.showCourseAtt(con, 0);
            } catch (Exception e)
            {
            }

        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        Teacher1 ob = new Teacher1();
        this.hide();
        ob.show();
    }//GEN-LAST:event_btn_backActionPerformed
    private JFrame frame;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_all;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_next;
    private javax.swing.JRadioButton btn_particular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_course;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_select_id;
    private javax.swing.JTextField txt_st_id;
    // End of variables declaration//GEN-END:variables
}
