/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Md. Ziad Karim
 */
public class Teacher1 extends javax.swing.JFrame {

    /**
     * Creates new form Teacher1
     */
    public Teacher1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        btn_show_info = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_take_att = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/teacher.png"))); // NOI18N
        jLabel1.setText(" Teacher");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 193, 1877, 115);

        btn_show_info.setBackground(new java.awt.Color(189, 209, 246));
        btn_show_info.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn_show_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/info.png"))); // NOI18N
        btn_show_info.setText("Show Info.");
        btn_show_info.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_show_info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_show_info.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_show_infoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_show_info);
        btn_show_info.setBounds(860, 630, 370, 80);

        btn_back.setBackground(new java.awt.Color(189, 209, 246));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/back.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(370, 630, 370, 80);

        btn_take_att.setBackground(new java.awt.Color(189, 209, 246));
        btn_take_att.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn_take_att.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/start.png"))); // NOI18N
        btn_take_att.setText("Take Att.");
        btn_take_att.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_take_att.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_take_att.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_take_attActionPerformed(evt);
            }
        });
        getContentPane().add(btn_take_att);
        btn_take_att.setBounds(1360, 630, 330, 80);

        btn_exit.setBackground(new java.awt.Color(189, 209, 246));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/exit.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(1504, 864, 185, 53);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/dark-blue-tech-circuit-board-technology-animated-background-video-graphic-design-ultra-hd-4k-3840x2160_sgelpuywg_thumbnail-full05.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 2000, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to exit?","Automated Attendance System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION )
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        Login Loginob= new Login(2);
        Login ob = new Login();
        ob.show();
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_show_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_infoActionPerformed
        //Teacher Teacherob;
        //Teacherob= new Teacher("Imtiaj Ahmed","CSE","CSE 4404");
        Teacher ob= new Teacher();
        ob.show();
        this.setVisible(false);
    }//GEN-LAST:event_btn_show_infoActionPerformed

    private void btn_take_attActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_take_attActionPerformed
    {//GEN-HEADEREND:event_btn_take_attActionPerformed
        start_attendence s = new start_attendence();
        s.show();
        this.hide();
    }//GEN-LAST:event_btn_take_attActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_show_info;
    private javax.swing.JButton btn_take_att;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
