/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Md. Ziad Karim
 */

public class WelcomePage extends javax.swing.JFrame {
    static int choice;
    

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }

public void login_page()
{
    Login Loginob= new Login();
        Loginob.show();
        
        this.setVisible(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel4 = new javax.swing.JLabel();
        btn_teacher = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_student = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_admin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automated Attendance System");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/teacher.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(860, 720, 60, 90);

        btn_teacher.setBackground(new java.awt.Color(189, 209, 246));
        btn_teacher.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_teacher.setText("    Teacher");
        btn_teacher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_teacher.setBorderPainted(false);
        btn_teacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_teacher.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_teacher.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_teacherActionPerformed(evt);
            }
        });
        getContentPane().add(btn_teacher);
        btn_teacher.setBounds(833, 716, 310, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/student.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1490, 720, 60, 90);

        btn_student.setBackground(new java.awt.Color(189, 209, 246));
        btn_student.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_student.setText("    Student");
        btn_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_student.setBorderPainted(false);
        btn_student.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_student.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_student.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_studentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_student);
        btn_student.setBounds(1458, 716, 330, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/admin.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 730, 50, 80);

        btn_admin.setBackground(new java.awt.Color(189, 209, 246));
        btn_admin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_admin.setText("    Admin");
        btn_admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_admin.setBorderPainted(false);
        btn_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_admin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_adminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_admin);
        btn_admin.setBounds(172, 718, 310, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/exit.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1630, 950, 50, 40);

        btn_exit.setBackground(new java.awt.Color(189, 209, 246));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setText("    Exit");
        btn_exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(1610, 940, 175, 58);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/icon_image.png"))); // NOI18N
        jLabel1.setText("Automated Attendance System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 1878, 530);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aas/dark-blue-tech-circuit-board-technology-animated-background-video-graphic-design-ultra-hd-4k-3840x2160_sgelpuywg_thumbnail-full05.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 2000, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to exit?","Automated Attendance System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION )
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        Login ob=new Login(1);
        login_page();
    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_teacherActionPerformed
       Login ob=new Login(2);
        login_page();
    }//GEN-LAST:event_btn_teacherActionPerformed

    private void btn_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentActionPerformed
       Login ob=new Login(3);
       login_page();
    }//GEN-LAST:event_btn_studentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_student;
    private javax.swing.JButton btn_teacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
